### ISSUE TITLE
Segmentation fault (core dumped) while running.

### ISSUE THREAD

**Issue by quantumxt** [smd-ros-devel/kangaroo_x2_driver#8]
Hi, I cloned this repository & managed to compile the driver without any error. 
But when I tried to run the node, it outputs the following:

> [ INFO] ...: Initializing
> [ INFO] ...: Starting
> [ INFO] ...: ...Done!
> Segmentation fault (core dumped)

Is it a pointer issue or something else? The port I used is _/dev/ttyUSB0_.
I'm using this driver with ROS Indigo, 64-bit Ubuntu 14.04.

**Comment by mattamert** [comment]
It's a bit difficult to diagnose the problem without actually being there; could you give us a bit more information about your ROS setup? For instance, are you sending Joint State or Joint Trajectory messages to the node when the segfault happens? If so, what are the contents of these messages? And what wheel names are you using?

**Comment by quantumxt** [comment]
Managed to resolve the problem, it was actually some hardware connection issue. Oops.
